/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 17 23:59:12 GMT 2026
 */

package com.opencsv;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.opencsv.CSVParser;
import com.opencsv.CSVReader;
import com.opencsv.ICSVParser;
import com.opencsv.RFC4180Parser;
import java.io.BufferedReader;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CSVReader_ESTest extends CSVReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringReader stringReader0 = new StringReader("Mr,KD");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, '!', '\'', false);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringReader stringReader0 = new StringReader("[\"9&");
      CSVParser cSVParser0 = new CSVParser('f', '\\', '?', true, true);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, (-1160), cSVParser0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StringReader stringReader0 = new StringReader("TA@");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'w', 'J');
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'w', '_', ',', 44, true, false, true);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0);
      bufferedReader0.close();
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StringReader stringReader0 = new StringReader("com.opencsv.stream.reader.LineReader");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 3);
      CSVParser cSVParser0 = new CSVParser('R', '!', '`');
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 0, cSVParser0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringReader stringReader0 = new StringReader("The separator character must be defined!");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0);
      CSVParser cSVParser0 = new CSVParser();
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, (-748), cSVParser0, false, false);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringReader stringReader0 = new StringReader("w/:l-pR");
      RFC4180Parser rFC4180Parser0 = new RFC4180Parser('n', 'f');
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 2040, rFC4180Parser0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, (-3312), (ICSVParser) null);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StringReader stringReader0 = new StringReader("com.opencsv.stream.reader.LineReader");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 3);
      CSVParser cSVParser0 = new CSVParser('R', ',', '`');
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 0, cSVParser0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StringReader stringReader0 = new StringReader("[\"9&");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      CSVParser cSVParser0 = new CSVParser('t');
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 4, cSVParser0, true, true);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StringReader stringReader0 = new StringReader("ihmyhT J(H");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'm', ')', 0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StringReader stringReader0 = new StringReader("EMPTY_QUOTES");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 'G', 'V', 'p', 1024, false, false);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RFC4180Parser rFC4180Parser0 = new RFC4180Parser('z', 'z');
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 2113, rFC4180Parser0, false, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, '+', '+', false);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, '-', '\"', true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StringReader stringReader0 = new StringReader("c^iJz/d");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'y', 'y', 3135);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 'x', 'k', (-785));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, ']', '~', ']', 0, false, false, false);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, '&', 'W', 'L', 0, true, true, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      StringReader stringReader0 = new StringReader("com.opencsv.CSVReader");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 10000);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 'i', 'i', 'i', 0, true, true);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, '?', 'H', '/', (-1), true, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 'n', 'n', 'n', (-1717), false);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 'P', 'Y', '|', (-1), true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 'r', 'S', '|', 630);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, '`', '`', '`');
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 'G', '|', '1');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 92);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, '<', '<');
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 's', '#');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, '\\');
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 'l');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      StringReader stringReader0 = new StringReader("g$I\u0004'%.AO");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) stringReader0, 'O', '0', 'A');
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, '^', 'c', '&', (-2271), true);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      StringReader stringReader0 = new StringReader("PQj_h+7}=8U9QR");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'e', 'o', '%', 10, true, false);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      StringReader stringReader0 = new StringReader("TW5wF@U");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 1);
      CSVParser cSVParser0 = new CSVParser();
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 302, cSVParser0, false, false);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      StringReader stringReader0 = new StringReader("com.opencsv.stream.reader.LineReader");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 3);
      CSVParser cSVParser0 = new CSVParser('R', '!', '`');
      cSVParser0.parseLineMulti("!Dw_7[AAz ");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 0, cSVParser0);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      StringReader stringReader0 = new StringReader("f38Hlv:");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'w', 'J');
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(stringReader0, 'w', 'F', ',', 44, true, false, true);
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      StringReader stringReader0 = new StringReader("EMPTY_SEPARATORS");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 'F');
       //  fail("Expecting exception: NoSuchFieldError");
       // Unstable assertion
      } catch(NoSuchFieldError e) {
         //
         // multilineLimit
         //
         verifyException("com.opencsv.CSVReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      StringReader stringReader0 = new StringReader("f");
      BufferedReader bufferedReader0 = new BufferedReader(stringReader0, 1);
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader(bufferedReader0, 'B', 'p', 'p', 'p');
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The separator, quote, and escape characters must be different!
         //
         verifyException("com.opencsv.CSVParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser('1');
      CSVReader cSVReader0 = null;
      try {
        cSVReader0 = new CSVReader((Reader) null, 128, cSVParser0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }
}
